// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAddress = "address"

// Address mapped from table <address>
type Address struct {
	ID        int64          `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true;comment:id" json:"id"`                 // id
	UserID    int64          `gorm:"column:user_id;type:int(10);not null;comment:用户id" json:"user_id"`                                   // 用户id
	Province  string         `gorm:"column:province;type:varchar(100);not null;comment:省" json:"province"`                               // 省
	City      string         `gorm:"column:city;type:varchar(100);not null;comment:市" json:"city"`                                       // 市
	County    string         `gorm:"column:county;type:varchar(100);not null;comment:县/区" json:"county"`                                 // 县/区
	Address   string         `gorm:"column:address;type:varchar(255);not null;comment:详细地址" json:"address"`                              // 详细地址
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:timestamp;comment:更新时间" json:"updated_at"`                                    // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:删除时间" json:"deleted_at"`                                    // 删除时间
	User      User           `gorm:"foreignKey:UserID;references:ID" json:"user"`
}

// TableName Address's table name
func (*Address) TableName() string {
	return TableNameAddress
}
