// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID                   int64          `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true;comment:?" json:"id"`                             // ?
	Phone                string         `gorm:"column:phone;type:char(11);not null;comment:手机号" json:"phone"`                                                  // 手机号
	Email                string         `gorm:"column:email;type:varchar(100);not null;comment:邮箱" json:"email"`                                               // 邮箱
	WechatUnionid        string         `gorm:"column:wechat_unionid;type:varchar(50);not null;comment:微信unionid" json:"wechat_unionid"`                       // 微信unionid
	WechatAppletOpenid   string         `gorm:"column:wechat_applet_openid;type:varchar(50);not null;comment:微信小程序id" json:"wechat_applet_openid"`             // 微信小程序id
	WechatOfficialOpenid string         `gorm:"column:wechat_official_openid;type:varchar(50);not null;comment:微信公众号id" json:"wechat_official_openid"`         // 微信公众号id
	Name                 string         `gorm:"column:name;type:varchar(15);not null;comment:姓名" json:"name"`                                                  // 姓名
	Nickname             string         `gorm:"column:nickname;type:varchar(30);not null;comment:昵称" json:"nickname"`                                          // 昵称
	Avatar               string         `gorm:"column:avatar;type:varchar(255);not null;comment:头像" json:"avatar"`                                             // 头像
	CreatedAt            time.Time      `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间;created_at" json:"created_at"` // 创建时间
	UpdatedAt            *time.Time     `gorm:"column:updated_at;type:timestamp;comment:更新时间;updated_at" json:"updated_at"`                                    // 更新时间
	DeletedAt            gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:删除时间" json:"deleted_at"`                                               // 删除时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
