// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserProfile = "user_profile"

// UserProfile mapped from table <user_profile>
type UserProfile struct {
	ID        int64          `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true;comment:id" json:"id"`                 // id
	UserID    int64          `gorm:"column:user_id;type:int(10) unsigned;not null;comment:用户id" json:"user_id"`                          // 用户id
	Gender    int64          `gorm:"column:gender;type:tinyint(1);not null;comment:性别：0保密 1 男 2女 3未知" json:"gender"`                     // 性别：0保密 1 男 2女 3未知
	Level     int64          `gorm:"column:level;type:tinyint(1);not null;comment:等级" json:"level"`                                      // 等级
	Password  string         `gorm:"column:password;type:char(32);not null;comment:密码" json:"password"`                                  // 密码
	Salt      string         `gorm:"column:salt;type:char(30);not null;comment:盐" json:"salt"`                                           // 盐
	Birthday  *time.Time     `gorm:"column:birthday;type:date;comment:出生日期" json:"birthday"`                                             // 出生日期
	Signature string         `gorm:"column:signature;type:varchar(255);not null;comment:个性签名" json:"signature"`                          // 个性签名
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:timestamp;comment:更新时间" json:"updated_at"`                                    // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName UserProfile's table name
func (*UserProfile) TableName() string {
	return TableNameUserProfile
}
